server:
  port: 8080

novel:
  filePath: "F:"

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel?useSSL=false
    username: root
    password: 134679
    initialsize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 10000
  jpa:
    show-sql: true
    database: MYSQL